"""Statistical testing for fairness: bootstrap CIs, permutation tests, FDR.

Provides three layers of statistical rigour for equity audit results:

1.  **BootstrapTest** — confidence intervals on per-group metrics and
    disparity ratios (mandatory for publication).
2.  **PermutationTest** — non-parametric hypothesis testing for group
    differences.
3.  **MultipleComparisonCorrector** — Benjamini–Hochberg FDR and
    Bonferroni corrections for the large number of tests generated by
    the 7-component × multi-strata audit.
"""

from __future__ import annotations

from typing import Any, Callable

import numpy as np
from numpy.typing import NDArray


class BootstrapTest:
    """Non-parametric bootstrap confidence intervals for per-group metrics.

    Args:
        n_bootstrap: Number of bootstrap resamples.
        ci_level: Confidence level (e.g. 0.95 for 95 % CI).
        seed: RNG seed for reproducibility.
    """

    def __init__(
        self,
        n_bootstrap: int = 2000,
        ci_level: float = 0.95,
        seed: int = 42,
    ) -> None:
        self.n_bootstrap = n_bootstrap
        self.ci_level = ci_level
        self.seed = seed

    def metric_ci(
        self,
        values: NDArray[np.floating[Any]],
        groups: NDArray[np.integer[Any]],
        metric_fn: Callable[[NDArray[np.floating[Any]]], float],
    ) -> dict[int, tuple[float, float, float]]:
        """Bootstrap CI for a metric computed per group.

        Args:
            values: 1-D array of metric inputs (e.g. absolute errors).
            groups: 1-D integer array of group labels (same length).
            metric_fn: Callable that takes a 1-D array and returns a
                scalar metric value (e.g. ``np.mean``).

        Returns:
            ``{group_id: (point_estimate, ci_lower, ci_upper)}``.
        """
        rng = np.random.default_rng(self.seed)
        alpha_half = (1.0 - self.ci_level) / 2.0
        unique_groups = np.unique(groups)
        results: dict[int, tuple[float, float, float]] = {}

        for g in unique_groups:
            mask = groups == g
            subset = values[mask]
            point = float(metric_fn(subset))

            boot_vals: list[float] = []
            n_g = len(subset)
            for _ in range(self.n_bootstrap):
                idx = rng.choice(n_g, size=n_g, replace=True)
                boot_vals.append(float(metric_fn(subset[idx])))

            ci_lo = float(np.percentile(boot_vals, 100.0 * alpha_half))
            ci_hi = float(np.percentile(boot_vals, 100.0 * (1.0 - alpha_half)))
            results[int(g)] = (round(point, 6), round(ci_lo, 6), round(ci_hi, 6))

        return results


class PermutationTest:
    """Non-parametric permutation test for group metric differences.

    Tests ``H₀: metric(group_a) == metric(group_b)`` by permuting
    group labels and computing the null distribution of the absolute
    difference.

    Args:
        n_permutations: Number of random permutations.
        seed: RNG seed for reproducibility.
    """

    def __init__(
        self,
        n_permutations: int = 5000,
        seed: int = 42,
    ) -> None:
        self.n_permutations = n_permutations
        self.seed = seed

    def test_difference(
        self,
        values_a: NDArray[np.floating[Any]],
        values_b: NDArray[np.floating[Any]],
        metric_fn: Callable[[NDArray[np.floating[Any]]], float],
    ) -> dict[str, float]:
        """Test whether two groups have significantly different metric values.

        Args:
            values_a: 1-D array of values for group A.
            values_b: 1-D array of values for group B.
            metric_fn: Scalar metric function.

        Returns:
            ``{"observed_diff": float, "p_value": float}``.
        """
        rng = np.random.default_rng(self.seed)
        observed_diff = abs(float(metric_fn(values_a)) - float(metric_fn(values_b)))

        combined = np.concatenate([values_a, values_b])
        n_a = len(values_a)

        null_diffs: list[float] = []
        for _ in range(self.n_permutations):
            perm = rng.permutation(len(combined))
            perm_a = combined[perm[:n_a]]
            perm_b = combined[perm[n_a:]]
            null_diffs.append(
                abs(float(metric_fn(perm_a)) - float(metric_fn(perm_b)))
            )

        null_arr = np.array(null_diffs)
        p_value = float((null_arr >= observed_diff).mean())

        return {
            "observed_diff": round(observed_diff, 6),
            "p_value": round(p_value, 6),
        }


class MultipleComparisonCorrector:
    """Correct p-values for multiple hypothesis tests.

    Provides Benjamini–Hochberg (FDR) and Bonferroni (FWER) corrections.
    BH-FDR is recommended for CIVIC-SAFE's 100+ audit tests.
    """

    @staticmethod
    def benjamini_hochberg(
        p_values: list[float],
        alpha: float = 0.05,
    ) -> list[dict[str, Any]]:
        """Benjamini–Hochberg FDR correction.

        More powerful than Bonferroni; controls the *false discovery
        rate* rather than the family-wise error rate.

        Args:
            p_values: Raw p-values from hypothesis tests.
            alpha: Significance level.

        Returns:
            List of dicts with ``raw_p``, ``adjusted_p``, ``significant``.
        """
        n = len(p_values)
        if n == 0:
            return []

        arr = np.array(p_values, dtype=np.float64)
        sorted_idx = np.argsort(arr)
        sorted_p = arr[sorted_idx]

        adjusted = np.zeros(n, dtype=np.float64)
        adjusted[n - 1] = sorted_p[n - 1]
        for i in range(n - 2, -1, -1):
            rank = i + 1
            adjusted[i] = min(sorted_p[i] * n / rank, adjusted[i + 1])
        adjusted = np.minimum(adjusted, 1.0)

        # Map back to original order
        result: list[dict[str, Any]] = [{}] * n
        for rank, orig_idx in enumerate(sorted_idx):
            result[orig_idx] = {
                "raw_p": round(float(p_values[orig_idx]), 6),
                "adjusted_p": round(float(adjusted[rank]), 6),
                "significant": bool(adjusted[rank] < alpha),
            }

        return result

    @staticmethod
    def bonferroni(
        p_values: list[float],
        alpha: float = 0.05,
    ) -> list[dict[str, Any]]:
        """Bonferroni FWER correction (conservative).

        Args:
            p_values: Raw p-values.
            alpha: Significance level.

        Returns:
            List of dicts with ``raw_p``, ``adjusted_p``, ``significant``.
        """
        n = len(p_values)
        return [
            {
                "raw_p": round(p, 6),
                "adjusted_p": round(min(p * n, 1.0), 6),
                "significant": bool(min(p * n, 1.0) < alpha),
            }
            for p in p_values
        ]
