"""Resilient loader for US Census ACS 5-Year Estimates."""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)


def load_acs_features(city: str, variables: list[str]) -> pd.DataFrame:
    """Load rigorously computed ACS variables.
    
    This function reads the state-of-the-art Geospatial Areal Interpolation 
    outputs generated by scripts/build_demographics.py.
    """
    logger.info(f"Attempting to load {len(variables)} rigorous ACS features for {city}...")
    
    project_root = Path(__file__).resolve().parent.parent.parent.parent
    demographics_file = project_root / "data" / "processed" / f"{city}_demographics.csv"
    
    if not demographics_file.exists():
        logger.error(f"FATAL: Rigorous demographic data for {city} not found.")
        logger.error("The previous 'simulated API timeout' has been removed to enforce World's Best scientific rigor.")
        logger.error(f"You MUST generate the data by running: python scripts/build_demographics.py")
        raise FileNotFoundError(f"Missing demographics file: {demographics_file}")
        
    df = pd.read_csv(demographics_file)
    logger.info(f"Successfully loaded true population-weighted demographics for {len(df)} spatial units.")
    return df
