#!/usr/bin/env python
"""Assemble a self-contained IEEE submission bundle under paper/submission_bundle/.

The bundle is a build artifact, not a hand-maintained copy: re-running this script
after editing the manuscript, regenerating tables, or refreshing figures produces
a bundle that is in sync by construction. Nothing inside it should be edited.

What it does:
  1. Copies the manuscript, rewriting \\graphicspath so figures resolve inside the
     bundle rather than through ../outputs/.
  2. Copies references.bib.
  3. Copies the seven converted table floats from paper/tables/.
  4. Copies exactly the figures the manuscript actually references -- parsed out of
     the .tex, not hardcoded -- so a bundle can never ship a stale or missing panel.
  5. Writes a README covering IEEEtran.cls, which is deliberately NOT vendored.

On IEEEtran.cls: it is a ~6000-line class by Michael Shell, distributed via CTAN
and the IEEE Author Center. We do not ship a copy and we certainly do not
hand-roll a "compatible" substitute -- that would silently typeset the paper in
something that is not IEEE format. Overleaf and the IEEE submission portals both
provide it natively, so the bundle compiles there as-is; the README says where to
get it for a local build.

Run:
    python scripts/build_submission_bundle.py
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PAPER = PROJECT_ROOT / "paper"
FIG_SRC = PROJECT_ROOT / "outputs" / "figures"
BUNDLE = PAPER / "submission_bundle"

MANUSCRIPT = "civic_safe_ieee.tex"
SUPPLEMENT = "civic_safe_supplementary.tex"
BIB = "references.bib"


BUNDLE_HEADER = """%% ====================================================================
%% CIVIC-SAFE -- IEEE Transactions submission manuscript
%% SELF-CONTAINED BUNDLE. Everything this file needs is in this folder.
%%
%% Requires IEEEtran.cls, which is NOT bundled: Overleaf and the IEEE
%% submission portals provide it, or install it from CTAN
%% (https://ctan.org/pkg/ieeetran) for a local build. See README.md.
%%
%% Compile:  pdflatex civic_safe_ieee -> bibtex civic_safe_ieee
%%           -> pdflatex civic_safe_ieee -> pdflatex civic_safe_ieee
%%
%%   figures/  the referenced panels
%%   tables/   the table floats, \\input below
%%
%% Generated by scripts/build_submission_bundle.py -- do not edit by hand.
%%
%% Deliberately pure ASCII. Accented names use LaTeX escapes (Cand\\`es,
%% P\\'olya) so it compiles without inputenc on any distribution.
%% ===================================================================="""


def rewrite_header(tex: str) -> str:
    """Replace the repo-oriented file header with bundle-oriented instructions.

    The in-repo header explains where tables come from and that figures live in
    ../outputs/. Neither is true or useful inside a bundle sent to a publisher.
    """
    lines = tex.splitlines(keepends=True)
    end = 0
    for i, line in enumerate(lines):
        if line.startswith("%%"):
            end = i + 1
        else:
            break
    if end == 0:
        return tex
    return BUNDLE_HEADER + "\n" + "".join(lines[end:])


def rewrite_graphicspath(tex: str) -> str:
    """Point \\graphicspath at the bundle's own figures/ directory.

    In the repository the manuscript reaches back to ../outputs/figures/. Inside
    the bundle that path does not exist, and while the existing fallback entries
    would still find figures/, leaving a dangling parent path in a file sent to a
    publisher invites confusion. Make it explicit.
    """
    pattern = re.compile(r"\\graphicspath\{[^\n]*\}")
    if not pattern.search(tex):
        raise SystemExit("no \\graphicspath found in the manuscript")
    tex = pattern.sub(r"\\graphicspath{{figures/}{./}}", tex, count=1)
    # The comment above graphicspath also describes the repo layout.
    return tex.replace(
        "% Figures live in outputs/figures/ in the repository. The extra entries let the\n"
        "% manuscript still build if paper/ is uploaded on its own with the figures\n"
        "% copied next to it (as when submitting to a publisher's LaTeX service).\n",
        "% Figures ship alongside this file in figures/.\n",
        1,
    )


def referenced_figures(tex: str) -> list[str]:
    """Every \\includegraphics target in the manuscript, in order of appearance."""
    return list(
        dict.fromkeys(
            m.group(1).strip()
            for m in re.finditer(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", tex)
        )
    )


def referenced_tables(tex: str) -> list[str]:
    """Every \\input target, normalised to a .tex filename."""
    names = []
    for m in re.finditer(r"\\input\{([^}]+)\}", tex):
        target = m.group(1).strip()
        name = Path(target).name
        names.append(name if name.endswith(".tex") else name + ".tex")
    return list(dict.fromkeys(names))


README = """# CIVIC-SAFE --- IEEE submission bundle

Self-contained LaTeX source for *Feedback-Corrected Conformal Prediction for
Spatiotemporal Crime Forecasting*. Generated by
`scripts/build_submission_bundle.py`; do not edit files here by hand, edit the
sources in `paper/` and re-run that script.

## Contents

```
civic_safe_ieee.tex             main manuscript (pure ASCII, no inputenc needed)
civic_safe_supplementary.tex    supplementary material, compiled separately
references.bib                  {n_refs} verified BibTeX entries
figures/                        {n_figs} figures, exactly those the manuscript cites
tables/                         {n_tabs} table floats, generated from outputs/tables/
```

The two `.tex` files are independent compilation units. Compile each in turn; the
supplementary shares `figures/` and needs no bibliography of its own.

## Compiling

The manuscript needs `IEEEtran.cls`, which is **not included here** and must not
be substituted with a look-alike --- a hand-written stand-in would typeset the
paper in something that is not IEEE format.

**Overleaf** (recommended): upload this folder as a project and compile. Overleaf
ships IEEEtran, so nothing further is required. Set the compiler to pdfLaTeX.

**IEEE submission portals** (ScholarOne / Author Center LaTeX service) likewise
provide IEEEtran; upload the folder as-is.

**Locally**, install it from CTAN first:

```
tlmgr install ieeetran          # TeX Live
mpm --install=ieeetran          # MiKTeX
```

or download `IEEEtran.cls` from <https://ctan.org/pkg/ieeetran> and place it
beside `civic_safe_ieee.tex`. Then:

```
pdflatex civic_safe_ieee
bibtex   civic_safe_ieee
pdflatex civic_safe_ieee
pdflatex civic_safe_ieee
```

Two pdflatex passes after bibtex are required: the first resolves citations, the
second settles cross-references and float placement.

## Packages used

`amsmath`, `amssymb`, `amsfonts`, `booktabs`, `graphicx`, `multirow`, `cite`,
`url`, `hyperref`. All are in a standard TeX Live or MiKTeX installation.
Theorem environments come from plain `\\newtheorem` plus IEEEtran's own
`IEEEproof`, deliberately not `amsthm`, whose `\\proof` collides with IEEEtran.

## Verification

`python scripts/validate_latex.py` with no arguments validates the main manuscript,
the supplementary and both bundle copies. It checks that every citation resolves to
a bib entry, every `\\ref` resolves to a `\\label`, and every `\\includegraphics`
target exists on disk. It is static analysis and does not replace compiling.
"""


def main() -> None:
    tex_src = PAPER / MANUSCRIPT
    if not tex_src.exists():
        raise SystemExit(f"manuscript not found: {tex_src}")
    tex = tex_src.read_text(encoding="utf-8")

    if BUNDLE.exists():
        shutil.rmtree(BUNDLE)
    (BUNDLE / "figures").mkdir(parents=True)
    (BUNDLE / "tables").mkdir(parents=True)

    # 1. manuscript, with bundle-local graphics path and header
    (BUNDLE / MANUSCRIPT).write_text(
        rewrite_header(rewrite_graphicspath(tex)), encoding="utf-8"
    )
    print(f"  manuscript      -> {MANUSCRIPT} (graphicspath + header rewritten)")

    # 1b. supplementary material, same graphicspath treatment. It shares the
    #     bundle's figures/ directory, and it is a separate compilation unit, so a
    #     publisher can drop it in as the supplementary PDF without edits.
    sup_src = PAPER / SUPPLEMENT
    if sup_src.exists():
        (BUNDLE / SUPPLEMENT).write_text(
            rewrite_graphicspath(sup_src.read_text(encoding="utf-8")),
            encoding="utf-8",
        )
        print(f"  supplementary   -> {SUPPLEMENT} (graphicspath rewritten)")
    else:
        print(f"  supplementary   -> SKIPPED, {SUPPLEMENT} not found")

    # 2. bibliography
    bib_src = PAPER / BIB
    shutil.copy2(bib_src, BUNDLE / BIB)
    n_refs = len(re.findall(r"@\w+\s*\{", bib_src.read_text(encoding="utf-8")))
    print(f"  bibliography    -> {BIB} ({n_refs} entries)")

    # 3. tables actually \input by the manuscript
    tabs = referenced_tables(tex)
    for name in tabs:
        src = PAPER / "tables" / name
        if not src.exists():
            raise SystemExit(
                f"manuscript inputs tables/{name} but it does not exist. "
                "Run scripts/build_paper_tables.py first."
            )
        shutil.copy2(src, BUNDLE / "tables" / name)
    print(f"  tables          -> {len(tabs)} file(s)")

    # 4. figures actually referenced, resolved the way LaTeX would
    figs = referenced_figures(tex)
    for name in figs:
        for cand in (FIG_SRC / name, PAPER / "figures" / name):
            if cand.exists():
                shutil.copy2(cand, BUNDLE / "figures" / name)
                break
        else:
            raise SystemExit(f"manuscript references {name} but it was not found")
    print(f"  figures         -> {len(figs)} file(s)")

    # 5. README, including the IEEEtran.cls situation
    (BUNDLE / "README.md").write_text(
        README.format(n_refs=n_refs, n_figs=len(figs), n_tabs=len(tabs)),
        encoding="utf-8",
    )
    print("  README.md       -> written (covers IEEEtran.cls acquisition)")

    total = sum(f.stat().st_size for f in BUNDLE.rglob("*") if f.is_file())
    n_files = sum(1 for f in BUNDLE.rglob("*") if f.is_file())
    print(f"\nbundle: {n_files} files, {total/1024:.0f} KiB -> "
          f"{BUNDLE.relative_to(PROJECT_ROOT)}")

    # Refresh the archive in the same breath. A zip built by hand goes stale the
    # moment the manuscript changes, and a stale zip uploaded to Overleaf compiles
    # the wrong paper silently -- the worst possible failure mode for a submission
    # artifact. Rebuilding it here makes drift impossible.
    archive = PAPER / "civic_safe_submission_bundle"
    zip_path = shutil.make_archive(str(archive), "zip", root_dir=str(BUNDLE))
    zp = Path(zip_path)
    print(f"archive: {zp.name}, {zp.stat().st_size/1024:.0f} KiB -> "
          f"{zp.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
